package com.example.app.di

import com.example.app.ai.AIService
import com.example.app.backend.FirebaseBackend
import com.example.app.data.local.AppDatabase
import com.example.app.repository.AIRepository
import com.example.app.repository.DataRepository
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import javax.inject.Singleton

/**
 * Dependency Injection - Hilt
 * Auto-generated by CodeCraft AI
 */

@Module
@InstallIn(SingletonComponent::class)
object AppModule {
    
    @Provides
    @Singleton
    fun provideAIService(): AIService {
        return AIService(apiKey = BuildConfig.GEMINI_API_KEY)
    }
    
    @Provides
    @Singleton
    fun provideFirebaseBackend(): FirebaseBackend {
        return FirebaseBackend()
    }
    
    @Provides
    @Singleton
    fun provideAppDatabase(): AppDatabase {
        return AppDatabase.getInstance()
    }
    
    @Provides
    @Singleton
    fun provideAIRepository(
        aiService: AIService,
        database: AppDatabase
    ): AIRepository {
        return AIRepository(aiService, database)
    }
    
    @Provides
    @Singleton
    fun provideDataRepository(
        backend: FirebaseBackend,
        database: AppDatabase
    ): DataRepository {
        return DataRepository(backend, database)
    }
}