package com.example.app.ui.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.app.repository.AIRepository
import com.example.app.repository.DataRepository
import com.example.app.repository.PromptType
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import javax.inject.Inject

/**
 * Modern ViewModel with StateFlow
 * Auto-generated by CodeCraft AI
 */

@HiltViewModel
class AIViewModel @Inject constructor(
    private val aiRepository: AIRepository,
    private val dataRepository: DataRepository
) : ViewModel() {
    
    private val _uiState = MutableStateFlow(AIUiState())
    val uiState: StateFlow<AIUiState> = _uiState.asStateFlow()
    
    fun sendMessage(message: String) {
        viewModelScope.launch {
            // Add user message
            val userMessage = ChatMessage(content = message, isUser = true)
            _uiState.update { it.copy(
                messages = it.messages + userMessage,
                isLoading = true,
                isStreaming = true,
                streamingText = ""
            )}
            
            // Get AI response with streaming
            aiRepository.generateTextStream(message)
                .catch { error ->
                    _uiState.update { it.copy(
                        isLoading = false,
                        isStreaming = false,
                        error = error.message
                    )}
                }
                .collect { streamingText ->
                    _uiState.update { it.copy(
                        streamingText = streamingText
                    )}
                }
            
            // Finalize streaming
            val finalText = _uiState.value.streamingText
            val aiMessage = ChatMessage(content = finalText, isUser = false)
            
            _uiState.update { it.copy(
                messages = it.messages + aiMessage,
                isLoading = false,
                isStreaming = false,
                streamingText = ""
            )}
            
            // Save conversation
            saveConversation(userMessage, aiMessage)
        }
    }
    
    fun generateWithTemplate(type: PromptType, content: String) {
        viewModelScope.launch {
            _uiState.update { it.copy(isLoading = true) }
            
            aiRepository.generateWithTemplate(type, content)
                .onSuccess { result ->
                    val message = ChatMessage(content = result, isUser = false)
                    _uiState.update { it.copy(
                        messages = it.messages + message,
                        isLoading = false
                    )}
                }
                .onFailure { error ->
                    _uiState.update { it.copy(
                        isLoading = false,
                        error = error.message
                    )}
                }
        }
    }
    
    private suspend fun saveConversation(userMsg: ChatMessage, aiMsg: ChatMessage) {
        val conversation = Conversation(
            id = System.currentTimeMillis().toString(),
            userMessage = userMsg.content,
            aiResponse = aiMsg.content,
            timestamp = System.currentTimeMillis()
        )
        
        dataRepository.saveData("conversations", conversation.id, conversation)
    }
    
    fun clearError() {
        _uiState.update { it.copy(error = null) }
    }
}

data class AIUiState(
    val messages: List<ChatMessage> = emptyList(),
    val isLoading: Boolean = false,
    val isStreaming: Boolean = false,
    val streamingText: String = "",
    val error: String? = null
)

data class Conversation(
    val id: String,
    val userMessage: String,
    val aiResponse: String,
    val timestamp: Long
)